Support italic in mono blocks
No font is registered to support a combination of italic and mono. This
adds those registrations, although I don't have the required fonts
at hand, so it simply uses the non-italic versions of the mono font,
effectively ignoring all italic formatting in mono blocks.

Fixes exception:

```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\cli.py", line 209, in <module>
    main()
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\cli.py", line 89, in main
    result = exporter.run(
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\channel_exporter.py", line 883, in run
    self._write_messages_to_pdf(document, messages, threads)
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\channel_exporter.py", line 538, in _write_messages_to_pdf
    last_user_id = self._parse_message_and_write_to_pdf(
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\channel_exporter.py", line 189, in _parse_message_and_write_to_pdf
    document.write_html(
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\fpdf_ext.py", line 90, in write_html
    self._open_tag(tag, attributes)
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\fpdf_ext.py", line 135, in _open_tag
    self.set_font(font_family, size=size, style=style)
  File "C:\Develop\slackchannel2pdf\fpdf_mod\fpdf.py", line 737, in set_font
    self.error("Undefined font: " + family + " " + style)
  File "C:\Develop\slackchannel2pdf\fpdf_mod\fpdf.py", line 286, in error
    raise RuntimeError("FPDF error: " + msg)
RuntimeError: FPDF error: Undefined font: notosansmono I
```