Dirty hack for unicode issues with PDF rendering
The PDF renderer for Python 3 encodes everything as latin1, which is
of course *very* unrealistic for Slack workspaces in an international
requirement.

This terrible hack replaces some common unicode modification codepoints
(e.g. for ´ and ` accents), at least ignoring them to prevent hard
crashes.

Fixes exception:
```
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\cli.py", line 209, in <module>
    main()
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\cli.py", line 89, in main
    result = exporter.run(
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\channel_exporter.py", line 889, in run
    document.output(str(filename_pdf))
  File "C:\Develop\slackchannel2pdf\fpdf_mod\fpdf.py", line 1325, in output
    buffer = self.buffer.encode("latin1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2028' in position 398771: ordinal not in range(256)
```