Ignore nested `<s>` tags in PDF rendering
The PDF renderer raised an exception if an `<s>` tag was nested. While
it's true that that's not supposed to occur, it does. I can't quite tell
why, but it is happening at lot, and on messages that only contain one
`<s>` tag, so I assume the `_last_font` must already be set outside the
message for some reason.

This change simply allows those nested tags, effectively ignoring the
nested tag, but at least moving on with the rendering nevertheless.

Fixes exception:
```
[...]
Traceback (most recent call last):
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\fpdf_ext.py", line 90, in write_html
    self._open_tag(tag, attributes)
  File "C:\Develop\slackchannel2pdf\slackchannel2pdf\fpdf_ext.py", line 112, in _open_tag
    raise HtmlConversionError("<s> tags can not be nested")
slackchannel2pdf.fpdf_ext.HtmlConversionError: <s> tags can not be nested

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
[...]
```
This one's nasty, because it causes another exception to occur while
handling this one.